# Collection -------------------------------------------------------------------
repo_staging_dir: "./repos"
yara_repositories:
  # Just for testing
  #- name: "YARA Style Guide"
  #  url: "https://github.com/Neo23x0/YARA-Style-Guide"
  #  author: "Florian Roth"
  #  quality: 80
  #  branch: "master"
#  - name: "Signature Base"
#    url: "https://github.com/Neo23x0/signature-base"
#    author: "Florian Roth"
#    quality: 85
#    branch: "master"
#    path: "yara"
  # License prevents the integration of the rules into the YARA-Forge
  #- name: "AvastTI"
  #  url: "https://github.com/avast/ioc"
  #  author: "Avast Threat Intel Team"
  #  quality: 90
  #  branch: "master"
#  - name: "ReversingLabs"
#    url: "https://github.com/reversinglabs/reversinglabs-yara-rules/"
#    author: "ReversingLabs"
#    quality: 90
#    branch: "develop"
#  - name: "Elastic"
#    url: "https://github.com/elastic/protections-artifacts/"
#    author: "Elastic"
#    quality: 75
#    branch: "main"
#  - name: "R3c0nst"
#    url: "https://github.com/fboldewin/YARA-rules/"
#    author: "Frank Boldewin"
#    quality: 90
#    branch: "master"
#  - name: "CAPE"
#    url: "https://github.com/kevoreilly/CAPEv2"
#    author: "Kevin O'Reilly"
#    quality: 65
#    branch: "master"
#    path: "data/yara"
#  - name: "BinaryAlert"
#    url: "https://github.com/airbnb/binaryalert/"
#    author: "Airbnb"
#    quality: 80
#    branch: "master"
#    path: "rules/public"
#  - name: "DeadBits"
#    url: "https://github.com/deadbits/yara-rules/"
#    author: "Adam Swanda"
#    quality: 80
#    branch: "master"
#    path: "rules"
#  - name: "DelivrTo"
#    url: "https://github.com/delivr-to/detections"
#    author: "Delivr.To"
#    quality: 80
#    branch: "main"
#    path: "yara-rules"
#  - name: "ESET"
#    url: "https://github.com/eset/malware-ioc"
#    author: "ESET TI"
#    quality: 80
#    branch: "master"
  - name: "FireEye-RT"
    url: "https://github.com/mandiant/red_team_tool_countermeasures/"
    author: "FireEye"
    quality: 75
    branch: "master"
    path: "rules"
  - name: "GCTI"
    url: "https://github.com/chronicle/GCTI"
    author: "gssincla@google.com"
    quality: 85
    branch: "main"
    path: "YARA"
  - name: "Malpedia"
    url: "https://github.com/malpedia/signator-rules/"
    author: "Felix Bilstein - yara-signator at cocacoding dot com"
    quality: 75
    branch: "main"
    path: "rules"
  - name: "McAfee ATR"
    url: "https://github.com/advanced-threat-research/Yara-Rules/"
    author: "McAfee ATR Team"
    quality: 70
    branch: "master"
  - name: "Arkbird SOLG"
    url: "https://github.com/StrangerealIntel/DailyIOC"
    author: "Arkbird_SOLG"
    quality: 75
    branch: "master"



# Quality Checks ---------------------------------------------------------------
# Explanations for the different issue levels used in the rule quality analysis
# Level 1 - cosmetic issues with the rule
# Level 2 - minor issues with the rule
# Level 3 - major issues with the rule
# Level 4 - critical issues with the rule

# Levels and quality score reduction
issue_levels:
   1: -5
   2: -25
   3: -70
   4: -100

# Rule Package Output ----------------------------------------------------------
yara_rule_packages:
  - name: "core"
    description: "Default YARA Rule Package - Core"
    minimum_quality: 70
    minimum_age: 7
  - name: "extended"
    description: "Default YARA Rule Package - Extended"
    minimum_quality: 50
    minimum_age: 1
  - name: "full"
    description: "Default YARA Rule Package - Full"
    minimum_quality: 20
    minimum_age: 0

rule_set_header: |
  /*
   * YARA-Forge YARA Rule Package
   * https://github.com/YARAHQ/yara-forge
   * 
   * Rule Package Information
   * Name: {rule_package_name} 
   * Description: {rule_package_description}
   * YARA-Forge Version: {program_version}
   * YARA-QA Commit: {yaraqa_commit}
   * Minimum Quality: {rule_package_minimum_quality}
   * Minimum Age (in days): {rule_package_minimum_age}
   * Creation Date: {retrieval_date}
   * Skipped: {total_rules_skipped_age} (age), {total_rules_skipped_quality} (quality)
   */

repo_header: |
  /*
   * YARA Rule Set
   * Repository Name: {repo_name}
   * Repository: {repo_url}
   * Retrieval Date: {retrieval_date}
   * Git Commit: {repo_commit}
   * Skipped: {total_rules_skipped_age} (age), {total_rules_skipped_quality} (quality)
   * 
   * LICENSE
   * 
   * {repo_license}
   */
